username: arendeiro
email: arendeiro@cemm.oeaw.ac.at
metadata:
  root_projects_dir: /scratch/lab_bock/shared/projects/
resources:
  genomes:
    2bit:
      hg19: /scratch/lab_bock/shared/resources/genomes/hg19/hg19.2bit
      hg38: /scratch/lab_bock/shared/resources/genomes/hg38/hg38.2bit
      mm10: /scratch/lab_bock/shared/resources/genomes/mm10/mm10.2bit
    fasta:
      hg19: /scratch/lab_bock/shared/resources/genomes/hg19/hg19.fa
      hg38: /scratch/lab_bock/shared/resources/genomes/hg38/hg38.fa
      mm10: /scratch/lab_bock/shared/resources/genomes/mm10/mm10.fa
  lola:
    region_databases:
      hg19:
        - /data/groups/lab_bock/shared/resources/regions/LOLACore/hg19/
        - /data/groups/lab_bock/shared/resources/regions/customRegionDB/hg19/
      hg38:
        - /data/groups/lab_bock/shared/resources/regions/LOLACore/hg38/
        - /data/groups/lab_bock/shared/resources/regions/customRegionDB/hg38/
      mm10:
        - /data/groups/lab_bock/shared/resources/regions/LOLACore/mm10/
        - /data/groups/lab_bock/shared/resources/regions/customRegionDB/mm10/
  meme:
    motif_databases:
      human: /scratch/lab_bock/shared/resources/motifs/motif_databases/HUMAN/HOCOMOCOv10.meme
      mouse: /scratch/lab_bock/shared/resources/motifs/motif_databases/MOUSE/uniprobe_mouse.meme
      vertebrate: /home/arendeiro/workspace/homer_4.8/data/knownTFs/vertebrates/known.motifs
    motif_id_mapping:
      mouse: /scratch/lab_bock/shared/resources/motifs/motif_databases/MOUSE/uniprobe_mouse.id_mapping.tsv
  enrichr:
    gene_set_libraries:
      - "GO_Biological_Process_2015"
      - "ChEA_2015"
      - "KEGG_2016"
      - "ESCAPE"
      - "Epigenomics_Roadmap_HM_ChIP-seq"
      - "ENCODE_TF_ChIP-seq_2015"
      - "ENCODE_and_ChEA_Consensus_TFs_from_ChIP-X"
      - "ENCODE_Histone_Modifications_2015"
      - "OMIM_Expanded"
      - "TF-LOF_Expression_from_GEO"
      - "Single_Gene_Perturbations_from_GEO_down"
      - "Single_Gene_Perturbations_from_GEO_up"
      - "Disease_Perturbations_from_GEO_down"
      - "Disease_Perturbations_from_GEO_up"
      - "Drug_Perturbations_from_GEO_down"
      - "Drug_Perturbations_from_GEO_up"
      - "WikiPathways_2016"
      - "Reactome_2016"
      - "BioCarta_2016"
      - "NCI-Nature_2016"
executables:
  twoBitToFa: twoBitToFa
  fasta-dinucleotide-shuffle: fasta-dinucleotide-shuffle
  ame: ame
  findMotifsGenome.pl: findMotifsGenome.pl
  compareMotifs.pl: compareMotifs.pl
